name: generate_pmtiles

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  data_daily_updating:
    runs-on: ubuntu-latest
    # continue-on-error: true
    steps:
      #### actions/checkout 
      - uses: actions/checkout@v3

      - run: docker pull ghcr.io/osgeo/gdal:ubuntu-small-3.8.3
