name: generate_pmtiles

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  data_daily_updating:
    runs-on: ubuntu-latest
    # continue-on-error: true
    steps:
      #### actions/checkout 
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          # cache: 'pip'

      # - run: docker pull osgeo/gdal # FULL VERSION
      - run: docker pull ghcr.io/osgeo/gdal:alpine-normal-latest
      - run: ls
      - run: docker run ghcr.io/osgeo/gdal:alpine-normal-latest ogrinfo --formats
      - run: docker run --rm -v /data:/data ghcr.io/osgeo/gdal:alpine-normal-latest ogrinfo data/osm_data.parquet
